global:
  scrape_interval:     15s
  evaluation_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'internal-monitor'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: top
    scrape_interval: 1s
    static_configs:                                                     # <-----------------------  system monitoring <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      - targets: ['localhost:9091']
